EmployeeRegister/Controllers/EmployeesController.cs
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using EmployeeRegister.Models;
using EmployeeRegister.ViewModels;
using EmployeeRegister.Interactors;
using System.Linq;

namespace EmployeeRegister.Controllers
{
    public class EmployeesController : Controller
    {
        private EmployeesInteractor employeeInteractor;

        public EmployeesController(EmployeesInteractor employeeInteractor)
        {
            this.employeeInteractor = employeeInteractor;
        }

        // GET: Employees
        public ActionResult Index(string filterByName, string filterByPosition, string filterByTaxIdentificationNumber)
        {
            List<EmployeeViewModel> viewModels = new List<EmployeeViewModel>();
            viewModels = employeeInteractor
                .ListEmployees()
                .Where(x => filterByName == null || (x.FirstName + " " + x.LastName).Contains(filterByName))
                .Where(x => filterByPosition == null || x.Position.Contains(filterByPosition))
                .Where(x => filterByTaxIdentificationNumber == null || x.TaxIdentificationNumber.Contains(filterByTaxIdentificationNumber))
                .Select(x => EmployeeViewModel.FromModel(x)).ToList();
            ViewBag.filterByName = filterByName;
            ViewBag.filterByPosition = filterByPosition;
            ViewBag.filterByTaxIdentificationNumber = filterByTaxIdentificationNumber;
            return View(viewModels);
        }

        // GET: Employees/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = employeeInteractor.FindById(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(EmployeeViewModel.FromModel(employee));
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstName,LastName,BirthDate,Position,TaxIdentificationNumber,Pay")] EmployeeViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {
                employeeInteractor.AddEmployee(employeeViewModel.ToModel());
                return RedirectToAction("Index");
            }

            return View(employeeViewModel);
        }

        public ActionResult NewRandom()
        {
            employeeInteractor.AddRandomEmployee();
            return RedirectToAction("Index");
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = employeeInteractor.FindById(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(EmployeeViewModel.FromModel(employee));
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,BirthDate,Position,TaxIdentificationNumber,Pay")] EmployeeViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {
                employeeInteractor.UpdateEmployee(employeeViewModel.ToModel());
                return RedirectToAction("Index");
            }
            return View(employeeViewModel);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = employeeInteractor.FindById(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(EmployeeViewModel.FromModel(employee));
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Employee employee = employeeInteractor.FindById(id);
            employeeInteractor.DeleteEmployee(employee);
            return RedirectToAction("Index");
        }
    }
}

EmployeeRegister/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Rejestr Pracowników</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Rejestr Pracowników", "Index", "Employees", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Informacje", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Marcin Szymura</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>